resource/my-vnet/vnet
resource/my-vnet/my-subnet/subnet
resource/my-dev-center/dev-center
resource/my-dev-center/my-azure-ad-attached-network/attached-network
resource/my-azure-ad-network-setting/network-setting
resource/my-devbox-definition/devbox-definition
resource/my-project/project
resource/my-project/my-pool/pool
resource/my-project/my-vm/virtual-machine
